-- Reglas permanentes verificadas de Comercio 130/75 y Sanidad 122/75.
-- Esta migracion solo completa el padron normativo: no modifica el motor,
-- escalas salariales, parametros legales ni liquidaciones historicas.
BEGIN;

INSERT INTO public.cct_regla_estructural
  (cct_numero,codigo,tipo,descripcion,articulo,configuracion,fuente,is_verified,version,activa)
VALUES
  ('130/75','ANTIGUEDAD','antiguedad','Adicional por antiguedad por cada ano trabajado','24',
   '{"porcentaje_por_anio":0.01,"base":"basico_convenio"}',
   'CCT 130/75 y modificatorios: https://www.argentina.gob.ar/normativa/nacional/norma-229939/texto',true,1,true),
  ('130/75','PRESENTISMO','presentismo','Asignacion complementaria por asistencia y puntualidad','40',
   '{"divisor":12,"base":["basico","antiguedad"],"requiere_control_asistencia":true}',
   'CCT 130/75 art. 40: https://www.argentina.gob.ar/normativa/nacional/norma-229939/texto',true,1,true),
  ('130/75','JORNADA','jornada','Jornada convencional completa y calculo de valor hora','8',
   '{"completa_horas_semanales":48,"divisor_horas_mensual":200,"admite_jornada_parcial":true}',
   'CCT 130/75: https://www.argentina.gob.ar/normativa/nacional/norma-229939/texto',true,1,true),

  ('122/75','ANTIGUEDAD','antiguedad','Adicional por antiguedad desde el primer ano','10',
   '{"porcentaje_por_anio":0.02,"base":"basico_categoria"}',
   'CCT 122/75: https://www.argentina.gob.ar/normativa/nacional/norma-143154/texto',true,1,true),
  ('122/75','FONDO_CIRUGIA_PARTO','adicional','Distribucion por cirugia mayor o parto','9',
   '{"automatizable":false,"dato_requerido":"cantidad de actos y personal participante"}',
   'CCT 122/75 art. 9: https://www.argentina.gob.ar/normativa/nacional/norma-143154/texto',true,1,true),
  ('122/75','TERAPIA_8H','adicional','Enfermeria en terapia, climax, coronaria, nursery o rinon artificial (8 h)','9',
   '{"automatizable":true,"porcentaje":0.20,"base":"basico_categoria","dato_requerido":"asignacion efectiva al sector"}',
   'CCT 122/75 art. 9: https://www.argentina.gob.ar/normativa/nacional/norma-143154/texto',true,1,true),
  ('122/75','MUCAMA_SECTOR_ESPECIAL','adicional','Mucama en sector especial','9',
   '{"automatizable":true,"porcentaje":0.10,"base":"basico_categoria","dato_requerido":"asignacion efectiva al sector"}',
   'CCT 122/75 art. 9: https://www.argentina.gob.ar/normativa/nacional/norma-143154/texto',true,1,true),
  ('122/75','MENTAL_ENFERMERIA','adicional','Atencion de enfermos mentales y nerviosos con tareas de enfermeria','9',
   '{"automatizable":true,"porcentaje":0.10,"base":"basico_categoria","dato_requerido":"tarea realizada"}',
   'CCT 122/75 art. 9: https://www.argentina.gob.ar/normativa/nacional/norma-143154/texto',true,1,true),
  ('122/75','MENTAL_TERAPIA','adicional','Terapia, vigilancia, aislamiento o sector intensivo de salud mental','9',
   '{"automatizable":true,"porcentaje":0.20,"base":"basico_categoria","dato_requerido":"tarea realizada"}',
   'CCT 122/75 art. 9: https://www.argentina.gob.ar/normativa/nacional/norma-143154/texto',true,1,true),
  ('122/75','MENTAL_OTRAS_TAREAS','adicional','Otras tareas en area de salud mental','9',
   '{"automatizable":true,"porcentaje":0.10,"base":"basico_categoria","dato_requerido":"tarea realizada"}',
   'CCT 122/75 art. 9: https://www.argentina.gob.ar/normativa/nacional/norma-143154/texto',true,1,true),
  ('122/75','ELECTRICISTA_TITULO','adicional','Electricista con titulo habilitante','9',
   '{"automatizable":true,"porcentaje":0.20,"base":"basico_categoria","dato_requerido":"titulo y tarea"}',
   'CCT 122/75 art. 9: https://www.argentina.gob.ar/normativa/nacional/norma-143154/texto',true,1,true),
  ('122/75','NOCTURNIDAD','adicional','Trabajo entre las 22:00 y las 06:00','9',
   '{"automatizable":true,"porcentaje":0.10,"base":"basico_categoria","prorrateo":"proporcion_periodo","dato_requerido":"horas nocturnas y horas totales"}',
   'CCT 122/75 art. 9: https://www.argentina.gob.ar/normativa/nacional/norma-143154/texto',true,1,true),
  ('122/75','OPERADOR_MAQUINAS_CONTABLES','adicional','Operador de maquinas contables','9',
   '{"automatizable":true,"porcentaje":0.20,"base":"basico_categoria","dato_requerido":"tarea realizada"}',
   'CCT 122/75 art. 9: https://www.argentina.gob.ar/normativa/nacional/norma-143154/texto',true,1,true),
  ('122/75','LAB_AREA_CERRADA','adicional','Laboratorio en area cerrada','9',
   '{"automatizable":true,"porcentaje":0.30,"base":"basico_categoria","dato_requerido":"area y tarea realizadas"}',
   'CCT 122/75 art. 9: https://www.argentina.gob.ar/normativa/nacional/norma-143154/texto',true,1,true),
  ('122/75','RAYOS_LAB_48H','jornada','Opcion de jornada de 48 horas en rayos o laboratorio','14',
   '{"automatizable":true,"porcentaje":0.33,"base":"basico_categoria","dato_requerido":"regimen de jornada documentado"}',
   'CCT 122/75 art. 14: https://www.argentina.gob.ar/normativa/nacional/norma-143154/texto',true,1,true),
  ('122/75','TAREA_SUPERIOR','tarea','Tarea de categoria superior','9',
   '{"automatizable":false,"dato_requerido":"categoria, horas y minimo convencional"}',
   'CCT 122/75 art. 9: https://www.argentina.gob.ar/normativa/nacional/norma-143154/texto',true,1,true),
  ('122/75','TAREA_NO_HABITUAL','tarea','Tarea no habitual','9',
   '{"automatizable":false,"dato_requerido":"horas y minimo convencional"}',
   'CCT 122/75 art. 9: https://www.argentina.gob.ar/normativa/nacional/norma-143154/texto',true,1,true),
  ('122/75','TAREA_ADICIONAL','tarea','Tarea adicional de otro puesto','9',
   '{"automatizable":false,"dato_requerido":"horas, puesto y exclusiones"}',
   'CCT 122/75 art. 9: https://www.argentina.gob.ar/normativa/nacional/norma-143154/texto',true,1,true),
  ('122/75','CAMAS_PACIENTES_EXCEDENTES','adicional','Recargo por camas, pacientes o gerontes excedentes','7',
   '{"automatizable":false,"dato_requerido":"dotacion, turno, sector y excedente"}',
   'CCT 122/75 art. 7: https://www.argentina.gob.ar/normativa/nacional/norma-143154/texto',true,1,true),
  ('122/75','ZONA_DESFAVORABLE','adicional','Zona desfavorable','13',
   '{"automatizable":false,"dato_requerido":"domicilio laboral y base convencional completa"}',
   'CCT 122/75 art. 13: https://www.argentina.gob.ar/normativa/nacional/norma-143154/texto',true,1,true),
  ('122/75','LICENCIA_ESPECIAL','licencia','Licencia adicional por exposicion o sector','22',
   '{"automatizable":false,"dato_requerido":"sector y tiempo anual de exposicion"}',
   'CCT 122/75 art. 22: https://www.argentina.gob.ar/normativa/nacional/norma-143154/texto',true,1,true),
  ('122/75','SALA_MATERNAL','reintegro','Reintegro por sala maternal','26',
   '{"automatizable":false,"dato_requerido":"obligacion legal, disponibilidad e hijos"}',
   'CCT 122/75 art. 26: https://www.argentina.gob.ar/normativa/nacional/norma-143154/texto',true,1,true),
  ('122/75','LAVADO_ROPA','reintegro','Reintegro por lavado y planchado de ropa','30',
   '{"automatizable":false,"dato_requerido":"acuerdo local y prestacion sustituida"}',
   'CCT 122/75 art. 30: https://www.argentina.gob.ar/normativa/nacional/norma-143154/texto',true,1,true)
ON CONFLICT (cct_numero,codigo,version) DO UPDATE SET
  tipo=EXCLUDED.tipo, descripcion=EXCLUDED.descripcion, articulo=EXCLUDED.articulo,
  configuracion=EXCLUDED.configuracion, fuente=EXCLUDED.fuente,
  is_verified=EXCLUDED.is_verified, activa=true;

COMMIT;
